# Generated by Django 4.0.1 on 2022-02-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
