# Generated by Django 4.0.1 on 2022-02-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_permission'),
        ('projects', '0011_remove_permission_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
