# Generated by Django 4.0.1 on 2022-02-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_permission_project_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='owner',
        ),
    ]
