# Generated by Django 4.0.1 on 2022-02-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_permission_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='permission',
            new_name='permissions',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
