# Generated by Django 4.0.1 on 2022-02-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_skill_name'),
        ('projects', '0021_remove_project_permissions_permission_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='sender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
