# Generated by Django 4.0.1 on 2022-02-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_permission_sender_alter_permission_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='project',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
