# Generated by Django 4.0.3 on 2022-07-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20220217_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('Edit', 'Edit permission'), ('Share', 'Share permission'), ('Delete', 'Delete permission')], max_length=50, null=True),
        ),
    ]
